name: Copy Workspace on Fork

on:
  workflow_dispatch:

jobs:
  copy-workspace:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: dentonzh/copy-on-fork
          ref: main
          path: app/workspace

      - name: Check if running on fork
        run : |
          if [[ "GITHUB_BASE_REF" == "$GITHUB_REF" ]]; then
            echo "Not running on fork. To protect main repository, exiting this workflow."
            exit 1
          fi
      
      - name: Copy workspace to root
        run: |
          ls
          cp -r . /

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Initialize workspace on new forked repository"
          git push origin main