name: Copy Workspace on Fork

on:
  fork:

jobs:
  copy-workspace:
    runs-on: ubuntu-latest
  
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: dentonzh/copy-on-fork
        ref: main
        path: copy-on-fork
    
    - name: Copy Workspace
      run: |
        cd app/workspace
        cp -r . /

    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Initialize workspace on new forked repository"
        git push origin main